/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apkdv_openssl_Tools */

#ifndef _Included_com_apkdv_openssl
#define _Included_com_apkdv_openssl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apkdv_openssl_Tools
 * Method:    init
 * Signature: LengYue
 */
JNIEXPORT jstring JNICALL Java_com_apkdv_openssl_Tools_StringFromJNI
        (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_apkdv_openssl_Tools_Encode
        (JNIEnv *env, jobject thiz, jstring strIn);

JNIEXPORT jstring JNICALL Java_com_apkdv_openssl_Tools_Decode
        (JNIEnv *env, jobject thiz, jstring strIn);

#ifdef __cplusplus
}
#endif
#endif
